### ISSUE TITLE
PurchaseDaoDB Raheleh

### ISSUE THREAD

**Issue by captainjus** [The-Software-Guild/c40finalproject-teem-5#1]
- [x]     Purchase getPurchaseById(int purchaseId);   //return a purchase object by id
- [x]     List<Purchase> getAllPurchases();   //return list of all purchases
- [x]     Purchase addPurchase(Purchase purchase);    //add a new purchase
- [x]     List<Purchase> getPurchaseRangeDate(LocalDate from, LocalDate to);  //return all purchases in date range

**Comment by rahelehzarei** [comment]
Done
